### ISSUE TITLE
crash leaves stale record 

### ISSUE THREAD

**Issue by mandric** [medic/medic-sentinel#43]
i submit a new record then started sentinel and got this crash:

```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: Parse Error
    at Socket.socketOnData (http.js:1520:20)
    at TCP.onread (net.js:510:27)
```

I restart sentinel and record is pretty much ignored by all transitions and remains stale/not updated by sentinel.

**Comment by garethbowen** [comment]
couchmark is dead. Closing.
