### ISSUE TITLE
Feature request: Add compatibility with "days since birth" for "Add Birth Date" trigger

### ISSUE THREAD

**Issue by bishwas-medic** [medic/medic-sentinel#84]
Currently, the webapp only uses the field denoting weeks since birth for determining the DOB of a child. While this works well for Immunization use cases, it is not ideal for PNC use cases where we need to track and send reminders within few days after the DOB. 

Therefore, requesting the support of a "days since birth" field for the "Add Birth Date" trigger for registration forms.

**Comment by abbyad** [comment]
Moving this feature request to medic-projects where other feature requests live.
